/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.switstack.switcloud.switcloudapi.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param rid
 * @param index
 * @param modulus
 * @param exponent
 * @param hash
 * @param name
 * @param hashType
 * @param algorithmType
 * @param expiresAt
 * @param organizationId
 */
@Serializable
data class CAPKCreateSchema(

    @SerialName(value = "rid")
    val rid: kotlin.String,

    @SerialName(value = "index")
    val index: kotlin.String,

    @SerialName(value = "modulus")
    val modulus: kotlin.String,

    @SerialName(value = "exponent")
    val exponent: kotlin.String,

    @SerialName(value = "hash")
    val hash: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @Contextual @SerialName(value = "hash_type")
    val hashType: CAPKHashType? = null,

    @Contextual @SerialName(value = "algorithm_type")
    val algorithmType: CAPKAlgorithmType? = null,

    @Contextual @SerialName(value = "expires_at")
    val expiresAt: java.time.LocalDate? = null,

    @Contextual @SerialName(value = "organization_id")
    val organizationId: java.util.UUID? = null

)
