/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.switstack.switcloud.switcloudapi.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param kernel
 * @param aid
 * @param tlv
 * @param name
 * @param technologyType
 * @param transactionType
 * @param asf
 * @param organizationId
 */
@Serializable
data class EMVCreateSchema(

    @SerialName(value = "kernel")
    val kernel: kotlin.String,

    @SerialName(value = "aid")
    val aid: kotlin.String,

    @SerialName(value = "tlv")
    val tlv: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @Contextual @SerialName(value = "technology_type")
    val technologyType: EMVTechnologyType? = null,

    @Contextual @SerialName(value = "transaction_type")
    val transactionType: EMVTransactionType? = null,

    @SerialName(value = "asf")
    val asf: kotlin.Boolean? = true,

    @Contextual @SerialName(value = "organization_id")
    val organizationId: java.util.UUID? = null

)
