/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.switstack.switcloud.switcloudapi.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * Values: _00,_01,_02,_09,_17,_20,_21,_93
 */
@Serializable
enum class EMVTransactionType(val value: kotlin.String) {

    @SerialName(value = "00")
    _00("00"),

    @SerialName(value = "01")
    _01("01"),

    @SerialName(value = "02")
    _02("02"),

    @SerialName(value = "09")
    _09("09"),

    @SerialName(value = "17")
    _17("17"),

    @SerialName(value = "20")
    _20("20"),

    @SerialName(value = "21")
    _21("21"),

    @SerialName(value = "93")
    _93("93");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is EMVTransactionType) "$data" else null

        /**
         * Returns a valid [EMVTransactionType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): EMVTransactionType? = data?.let {
            val normalizedData = "$it".lowercase()
            entries.firstOrNull { value ->
                it == value || normalizedData == "$value".lowercase()
            }
        }
    }
}
