name: ci

on:
  push:
    branches:
      - 'develop'
      - 'main'
      - 'release/*'
    tags:
      - '**'
  pull_request:
  pull_request_review:
    types: [submitted]
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: build-and-publish
        uses: switstack/switstack-reusables-workflows/.github/actions/build-and-publish@main
        with:
          checkout-token: ${{ secrets.GA_CLONE_REPOS }}
          vpn-dns-server: ${{ vars.VPN_DNS_SERVER }}
          vpn-dns-domain: ${{ vars.VPN_DNS_DOMAIN }}
          ovpn-config: ${{ secrets.OVPN_CONFIG }}
