name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
  pull_request:
    types: [edited]

concurrency:
  group: renovate-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  renovate:
    if: github.event_name != 'pull_request' || startsWith(github.event.pull_request.head.ref, 'renovate/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create Renovate Cache Directory
        run: |
          mkdir -p /tmp/renovate/cache
          chmod 777 /tmp/renovate/cache

      - name: Run Renovate
        env:
          LOG_LEVEL: info
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_PAT_TOKEN }}
        run: |
          docker run \
            --rm \
            --network host \
            -e LOG_LEVEL="${LOG_LEVEL}" \
            -e RENOVATE_REPOSITORIES="${{ github.repository }}" \
            -e RENOVATE_TOKEN="${RENOVATE_TOKEN}" \
            -v "$(pwd)/renovate.json:/usr/src/app/config.json:ro" \
            -v "/tmp/renovate/cache:/tmp/renovate/cache:rw" \
            ghcr.io/renovatebot/renovate:latest
